### ISSUE TITLE
Crash when trying to login on fosscord

### ISSUE THREAD

**Issue by keneshindev** [X1nto/OpenCord#13]
It seems like it cannot deserialize captcha response which does not exist on fosscord
```
01-27 02:05:12.272 E/AndroidRuntime(11588): FATAL EXCEPTION: DefaultDispatcher-worker-1
01-27 02:05:12.272 E/AndroidRuntime(11588): Process: com.xinto.opencord.kenecord, PID: 11588
01-27 02:05:12.272 E/AndroidRuntime(11588): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.Gson.fromJson(Gson.java:963)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.Gson.fromJson(Gson.java:928)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.Gson.fromJson(Gson.java:877)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.Gson.fromJson(Gson.java:848)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.xinto.opencord.ui.screens.login.LoginScreenKt$LoginScreen$2$1$3$1.invokeSuspend(LoginScreen.kt:187)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
01-27 02:05:12.272 E/AndroidRuntime(11588): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
01-27 02:05:12.272 E/AndroidRuntime(11588): 	... 11 more
```

**Comment by X1nto** [comment]
It should only fall back to captcha when it's necessary. If there's no captcha in the first place, it should just let you login. I'll take a look.

**Comment by Austcool-Walker** [comment]
I believe I have had this same issue.

**Comment by Einstein-here** [comment]
Same here am experiencing the same problem. 

I tried using the application with no presence of fosscord, but even that failed, captcha appears but it keep loading until the application fails and it crashes again

**Comment by AnonNeedsAssist** [comment]
On login,.it gets stuck on a blank screen for me.

**Comment by X1nto** [comment]
Should be fixed now, however, some of the Fosscord's API responses aren't directly compatible with Discord's, hence stuff might fail to load.
